INSERT INTO CATEGORY (description) VALUES ('American');
INSERT INTO CATEGORY (description) VALUES ('Italian');
INSERT INTO CATEGORY (description) VALUES ('Mexican');
INSERT INTO CATEGORY (description) VALUES ('Fast Food');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Ounce');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (unit_of_measure) VALUES ('Pint');